---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"]
      - id: trailing-whitespace
        exclude: "^datasets/pinochet-rettig/semantics/mapping.protege.obda"
      - id: detect-private-key
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.15.20"
    hooks:
      - id: ruff
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.2.2
    hooks:
      - id: sqlfluff-fix
        additional_dependencies: ["dbt-postgres<2", "sqlfluff-templater-dbt", "dbt-core<2"]
      - id: sqlfluff-lint
        additional_dependencies: ["dbt-postgres<2", "sqlfluff-templater-dbt", "dbt-core<2"]
fail_fast: false
files: ".*"
exclude: "desktop.ini" # Windows
default_language_version:
  python: python3.13
