version: "3.7"
name: pinochet

services:
  postgis:
    image: postgis/postgis:15-3.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinochet
    ports:
      - 5433:5432

volumes:
  pgdata:
