version: '3.4'

services:
  ontop:
    image: ghcr.io/diegoquintanav/pinochet-sparql-ontop:latest
    build:
      context: services/ontop
      dockerfile: Dockerfile
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/mapping.protege.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mapping.protege.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/mapping.protege.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/mapping.protege.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      # files needed by ontop to map the ontology to the db
      - ./services/ontop/semantics:/opt/ontop/input
      # postgres jdbc driver to connect to postgis
      - ./services/ontop/jdbc:/opt/ontop/jdbc
    ports:
      - "8083:8080"
