version: "3.7"
name: pinochet

services:
  cache:
    image: redis:6

  directus:
    image: directus/directus:10.6.1
    ports:
      - 8055:8055
    volumes:
      - ./services/directus/uploads:/directus/uploads
      # If you want to load extensions from the host
      - ./services/directus/extensions:/directus/extensions
    depends_on:
      - cache
      - postgis
    environment:
      # openssl rand -hex 16
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: pg
      DB_HOST: postgis
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}

      CACHE_ENABLED: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: http://0.0.0.0:8055
