version: "3.9"
name: pinochet

services:
  postgis:
    image: postgis/postgis:15-3.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432

volumes:
  pgdata:
    driver: local
