version: "3.3"
services:
  streamlit:
    image: ghcr.io/diegoquintanav/pinochet-streamlit:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
    build:
      context: ./services/streamlit
    ports:
      - 8501:8501
    volumes:
      - streamlit-cachedata:/root/.cache
      - ./services/streamlit/src/:/src/
      - streamlit-venv:/home/daniellopez/.venv

volumes:
  streamlit-cachedata:
    driver: local
  streamlit-venv:
    driver: local
