version: "3.3"
services:
  streamlit:
    image: ghcr.io/diegoquintanav/pinochet-rettig-streamlit:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
    build:
      context: ./pinochet-rettig-streamlit
    ports:
      - 8501:8501
    volumes:
      - streamlit-cachedata:/root/.cache
      - ./pinochet-rettig-streamlit/streamlit_app.py:/src/streamlit_app.py
      - ./pinochet-rettig-streamlit/requirements.txt:/src/requirements.txt
      - ./pinochet-rettig-streamlit/.streamlit/config.toml:/src/.streamlit/config.toml
      - streamlit-venv:/home/daniellopez/.venv

volumes:
  streamlit-cachedata:
    driver: local
  streamlit-venv:
    driver: local
