version: "3.9"
name: pinochet

services:
  superset:
    networks:
      - default
      - nw_pinochet
  superset-worker:
    networks:
      - default
      - nw_pinochet
  postgis:
    networks:
      - default
      - nw_pinochet

networks:
  default:
    driver: bridge
  nw_pinochet:
    driver: bridge
