version: '3.4'

services:
  ontop:
    image: ontop/ontop
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/mapping.protege.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/mapping.protege.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/mapping.protege.properties
      ONTOP_PORTAL_FILE: /opt/ontop/input/mapping.protege.portal.toml
      ONTOP_CORS_ALLOWED_ORIGINS: "*"
      ONTOP_DEV_MODE: "true"
    volumes:
      # we map the properties file separately because db hostname and port change internally
      - ./services/ontop/input/mapping.protege.properties:/opt/ontop/input/mapping.protege.properties
      # files needed by ontop to map the ontology to the db
      - ./datasets/pinochet-rettig/semantics:/opt/ontop/input
      # postgres jdbc driver to connect to postgis
      - ./services/ontop/jdbc:/opt/ontop/jdbc
    ports:
      - "8083:8080"
