version: 2

seeds:
  - name: pinochet_raw
    description: Raw pinochet dataset
    notes: https://github.com/danilofreire/pinochet/blob/master/data/pinochet.csv
    columns:
      - name: individual_id
        type: text not null
      - name: group_id
        type: text not null
      - name: start_date_daily
        type: text
      - name: end_date_daily
        type: text
      - name: start_date_monthly
        type: text
      - name: end_date_monthly
        type: text
      - name: last_name
        type: text
      - name: first_name
        type: text
      - name: minor
        type: text
      - name: age
        type: text
      - name: male
        type: text
      - name: occupation
        type: text
      - name: occupation_detail
        type: text
      - name: victim_affiliation
        type: text
      - name: victim_affiliation_detail
        type: text
      - name: violence
        type: text
      - name: method
        type: text
      - name: interrogation
        type: text
      - name: torture
        type: text
      - name: mistreatment
        type: text
      - name: targeted
        type: text
      - name: press
        type: text
      - name: war_tribunal
        type: text
      - name: number_previous_arrests
        type: text
      - name: perpetrator_affiliation
        type: text
      - name: perpetrator_affiliation_detail
        type: text
      - name: nationality
        type: text
      - name: place_1
        type: text
      - name: start_location_1
        type: text
      - name: latitude_1
        type: text
      - name: longitude_1
        type: text
      - name: exact_coordinates_1
        type: text
      - name: place_2
        type: text
      - name: location_2
        type: text
      - name: latitude_2
        type: text
      - name: longitude_2
        type: text
      - name: exact_coordinates_2
        type: text
      - name: place_3
        type: text
      - name: end_location_3
        type: text
      - name: latitude_3
        type: text
      - name: longitude_3
        type: text
      - name: exact_coordinates_3
        type: text
      - name: place_4
        type: text
      - name: end_location_4
        type: text
      - name: latitude_4
        type: text
      - name: longitude_4
        type: text
      - name: exact_coordinates_4
        type: text
      - name: place_5
        type: text
      - name: end_location_5
        type: text
      - name: latitude_5
        type: text
      - name: longitude_5
        type: text
      - name: exact_coordinates_5
        type: text
      - name: place_6
        type: text
      - name: end_location_6
        type: text
      - name: latitude_6
        type: text
      - name: longitude_6
        type: text
      - name: exact_coordinates_6
        type: text
      - name: page
        type: text
      - name: additional_comments
        type: text
        description: >
          This variable gives additional information about cases that are
          too ambiguous to fit precisely into a single category. For instance, when the Truth and
          Commission Report is unsure whether the victim was killed or committed suicide, or if a
          given human rights abuse may have occurred in Santiago or elsewhere. Only 10 cases have
          additional information.
