[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Diego Quintana <daquintanav@gmail.com>"]
readme = "README.md"
packages = [
    { include = "pinochet", from = "src" },
]

[tool.poetry.scripts]
pinochet-api-cli = "pinochet.cli:app"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.115.2"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
sqlalchemy = "^2.0.23"
alembic = "^1.12.1"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
typer = "^0.9.0"
psycopg2-binary = "^2.9.9"
tenacity = "^8.2.3"
strawberry-graphql = {extras = ["debug-server", "fastapi"], version = "^0.216.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
loguru = "^0.7.2"
fastapi-healthz = "^1.0.0"
python-decouple = "^3.8"


[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
ruff = "^0.1.5"
pytest = "^7.4.3"
ipykernel = "^6.29.4"
pandas = "^2.2.2"
httpx = "^0.27.0"
sqlalchemy-model-faker = "^0.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
