title="University Demo"

[[tabGroups]]

name="Example Queries"

[[tabGroups.tabs]]

name="get the last names of victims"
query="""
PREFIX : <http://example.org/pinochet-rettig#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?victim ?lastName {
  ?victim a :Victim ; :hasLastName ?lastName .
}
"""
