dbt_pinochet:
  outputs:
    
    dev:
      type: postgres
      threads: 1
      host: 0.0.0.0
      port: 5433
      user: postgres
      pass: postgres
      dbname: pinochet
      schema: dbt_dev

    api:
      type: postgres
      threads: 1
      host: 0.0.0.0
      port: 5433
      user: postgres
      pass: postgres
      dbname: pinochet
      schema: api

    prod:
      type: postgres
      threads: 1
      host: "{{ env_var('DBT_DB_PINOCHET_PROD_HOST') }}"
      port: "{{ env_var('DBT_DB_PINOCHET_PROD_PORT') }}"
      user: "{{ env_var('DBT_DB_PINOCHET_PROD_USERNAME') }}"
      pass: "{{ env_var('DBT_DB_PINOCHET_PROD_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DB_PINOCHET_DBNAME') }}"
      schema: "{{ env_var('DBT_DB_PINOCHET_PROD_SCHEMA') }}"

  target: dev
